### ISSUE TITLE
ios 调用sendMessage 时 真机闪退

### ISSUE THREAD

**Issue by senmao1994** [JiangJuHong/FlutterTencentImPlugin#158]
![image](https://user-images.githubusercontent.com/50578587/141994420-aa4c609b-d2fb-4890-8a67-ab78b47d425c.png)
在调用sendmessage ios真机闪退
发送文本相关代码
![image](https://user-images.githubusercontent.com/50578587/141995138-b58487d3-027c-44dc-a999-93c23ffa1876.png)

系统版本 15.0.1
手机型号 iphone 11 pro
Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale zh-Hans-CN)

**Comment by JiangJuHong** [comment]
这是一个已经被修复的bug，但是还没有发布，请使用 git 方式引入最新 ref ，如:
````
  tencent_im_plugin:
    git:
      url: https://github.com/JiangJuHong/FlutterTencentImPlugin
      ref: f7ade116a2a04db35cd9a5fca030ad83e900e63a
````
